# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d32340ea0c9f5c35529433b0adcee2cc3f57abe957c3a057d58551e6cecbb3a9450eacf5e6173e7614d611985628c272ddc08d142f07bf214751bfd03c77e61a

test:
  secret_key_base: 7812b5d38358733198d44039c1de42c72aa299cc027336a01a56a16e58efce649099ec0170afcf43e5d125935531d8b057375f4ef63a18c31c3b3b60bd3ecdeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
